### ISSUE TITLE
Be able to scroll/page through doc values (and terms).

### ISSUE THREAD

**Issue by noofherder** [flaxsearch/marple#18]

**Comment by romseygeek** [comment]
We want two different views for Sorted and SortedSet values.
1) The current per-document view, although it would be nice to make it more tabular, like so:

| docid | values |
| ---- | ----- |
| 1  | ord1 value1 |
| | ord2 value2 |
| 2 | ord2 value2 |

2) A list of values, with their ords:

| ord | value |
| -- | -- |
| 0 | value0 |
| 1 | value1 |

**Comment by noofherder** [comment]
For scrolling, I will add a "load more" link to terms and docvalues for now, as it's the simplest design.

**Comment by romseygeek** [comment]
I think we can close this now?  It's implemented for docvalues, and we have a separate issue for terms
