### ISSUE TITLE
AutomatonTermsEnum throws a NPE

### ISSUE THREAD

**Issue by noofherder** [flaxsearch/marple#24]
This happens when the regexp has no trailing .*, even when it matches a value. e.g.:

http://localhost:8080/api/docvalues/dv_filename_set/ordered?filter=README

but add a .* and it works. Is this a Lucene bug?

! java.lang.NullPointerException: null
! at org.apache.lucene.index.AutomatonTermsEnum.<init>(AutomatonTermsEnum.java:79)
! at com.github.flaxsearch.resources.DocValuesResource.getOrderedDocValues(DocValuesResource.java:174)

**Comment by romseygeek** [comment]
Hm, this does look like a problem with lucene - AutomatonTermsEnum doesn't work with a fixed-string automaton.

As a workaround, maybe we should just always add a ```.*``` to the end of the passed-in filter, making it always be a prefix filter?

**Comment by romseygeek** [comment]
I've opened a ticket in lucene: https://issues.apache.org/jira/browse/LUCENE-7627

**Comment by romseygeek** [comment]
Is this fixed within the webapp, or just in the UI?

**Comment by noofherder** [comment]
It's fixed in the webapp. Try the example link.
